export const IndonesianUniversities = [
  "Universitas Indonesia (UI)",
  "Institut Teknologi Bandung (ITB)",
  "Universitas Gadjah Mada (UGM)",
  "Institut Pertanian Bogor (IPB)",
  "Universitas Airlangga (Unair)",
  "Universitas Diponegoro (Undip)",
  "Institut Teknologi Sepuluh Nopember (ITS)",
  "Universitas Padjadjaran (Unpad)",
  "Universitas Brawijaya (UB)",
  "Universitas Sebelas Maret (UNS)",
  "Universitas Hasanuddin (Unhas)",
  "Universitas Sumatera Utara (USU)",
  "Universitas Telkom",
  "Universitas Bina Nusantara (Binus)",
  "Universitas Katolik Indonesia Atma Jaya",
  "Universitas Pendidikan Indonesia (UPI)",
  "Universitas Negeri Jakarta (UNJ)",
  "Universitas Negeri Yogyakarta (UNY)",
  "Universitas Islam Negeri (UIN) Syarif Hidayatullah",
  "Universitas Trunojoyo Madura (UTM)",
  "IAIN Madura",
  "Universitas Islam Madura (UIM)",
  "Universitas Madura (UNIRA)",
  "Universitas Wiraraja (UNIJA)",
  "Universitas KH Bahaudin Mudhary Madura (UNIBA)",
  "Politeknik Negeri Madura (POLTERA)",
  "Institut Dirosah Islamiyah Al-Amien (IDIA)",
  "Institut Ilmu Keislaman Annuqayah (Instika)",
  "STKIP PGRI Sumenep"
];
